apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gnylc6o17-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gnylc6o17-nodejs 
  name: gnylc6o17-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: gnylc6o17-nodejs 
